[package]
name = "block-chain-example-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.5"
itertools = "0.10.1"
chrono = "0.4.19"
once_cell = "1.8.0"